#! /usr/bin/env python3

import numpy as np

rawval_for_0 = 8939.2
rawval_for_10 = 15579.1

def read_dat(filename):
    result = []
    with open(filename) as inf:
        for row in inf:
            cols = row.split()
            ts = float(cols[0])
            rawval = -int(cols[1])
            result.append([ts, rawval])
    return result

def get_rawvals(dat):
    vals = []
    for row in dat:
        vals.append(row[1])
    return vals

dat_files = [
    "ref-0a.dat",
    "ref-0b.dat",
    "ref-0c.dat",
    "ref-10.dat",
    "ref-278.7.dat",
    "ref-82.9.dat"
]

def print_raw_stats():
    for dat_file in dat_files:
        dat = read_dat (dat_file)
        vals = np.array(get_rawvals(dat))
        mean = vals.mean()
        std = vals.std()
        print("{:15s} {:8.1f} {:8.1f} {:8.2f}%".format(
            dat_file, mean, std, std/mean*100))

def raw_to_grams(val):
    return (val - rawval_for_0) / (rawval_for_10 - rawval_for_0) * 10

def lpf_step (val, newval, dt, tc):
    factor = 2 * 3.1416 * 1/tc * dt;
    if factor > 1:
        factor = 1;
    return val * (1 - factor) + newval * factor

def write_dat(file, arr):
    with open(file,"w") as outf:
        for row in arr:
            print(row[0], row[1], file=outf)

def convert_grams(file):
    dat = read_dat (file)
    grams = []
    for row in dat:
        ts = row[0]
        grams.append([ts,raw_to_grams(row[1])])
    return grams

def do_lpf():
    lpf = []
    tc = 1
    grams = 0
    for row in unfiltered:
        ts = row[0]
        if len(lpf) == 0:
            dt = .1
        else:
            dt = ts - last
        last = ts
        grams = lpf_step (grams, row[1], dt, tc)
        lpf.append([ts, grams])
    return lpf

unfiltered = convert_grams ("filter-raw.dat")
write_dat ("unfiltered.dat", unfiltered)

lpf = do_lpf()
write_dat ("lpf.dat", lpf)


from filterpy.kalman import KalmanFilter
from filterpy.common import Q_discrete_white_noise

kf = KalmanFilter(dim_x=2, dim_z=1)
# grams, grams velocity
kf.x = np.array([
    [0.0],
    [0.0]
    ])

# state transition matrix
kf.F = np.array([
    [1., 1.],
    [0., 1.]
    ])

# measurement function
kf.H = np.array ([
    [1., 0.]
    ])

# covariance matrix
kf.P = np.array([
    [100**2,     0],
    [    0, .1**2]
    ]);

# state uncertainty
kf.R = 2**2

# process uncertainty
kf.Q = np.array([
    [.1**2,   .001],
    [  .001,     2**2]
    ]);

filtered_g = []
filtered_gdot = []
last_grams = unfiltered[0][1]
for row in unfiltered:
    ts = row[0]
    grams = row[1]
    
    if abs(grams - kf.x[0][0]) > 50:
        continue

    kf.predict()
    kf.update([grams])

    g = kf.x[0][0]
    gdot = kf.x[1][0]
    
    filtered_g.append([ts, g])
    filtered_gdot.append([ts, gdot])

write_dat ("g.dat", filtered_g)
write_dat ("gdot.dat", filtered_gdot)
    



